version: '3.7'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: fRiend_prod
      MYSQL_USER: prod
      MYSQL_PASSWORD: prod

  payment_server:
    image: suejungshin/payment-calculator
    depends_on:
      - 'database'
    ports:
      - '80:3001'